language: generic

services:
  - docker

before_install:
  - mkdir -p /home/travis/.config/getready/default/Dockerfile
  - echo "FROM getready/base" >> /home/travis/.config/getready/default/Dockerfile

script:
  - ./get-ready.sh bats tests
